[{
  "id": 4,
  "name": "Open Sesame Password Generator",
  "description": "lorem ipsumd dbaiugleaajncja gdkdiugba gsi",
  "image": "https://reactgifsportfolio.s3.us-east-2.amazonaws.com/PasswordGenerator.gif",
  "gitHubLink": "https://github.com/izztnkr/Open-Sesame-Generator",
  "deployedLink": "https://izztnkr.github.io/Open-Sesame-Generator/",
  "techType": "MERN Stack",
  "tech1":"https://reactgifsportfolio.s3.us-east-2.amazonaws.com/javascriptlogo.png",
  "tech2":"https://reactgifsportfolio.s3.us-east-2.amazonaws.com/HTMLlogo.png",
  "tech3":"https://reactgifsportfolio.s3.us-east-2.amazonaws.com/vscodeLogo.png",
  "tech4":"https://reactgifsportfolio.s3.us-east-2.amazonaws.com/githubLogo.png", 
  "tech5":"",
  "tech6":"",
  "tech7":"",
  "tech8":"",
  "tech9":"",
  "tech10":"",
  "tech11":"",
  "tech12":""
},
{
  "id": 5,
  "name": "Daily Planner App",
  "description": "lorem ipsumd dbaiugleaajncja gdkdiugba gsi",
  "image": "https://reactgifsportfolio.s3.us-east-2.amazonaws.com/WorkDayScheduler.gif",
  "gitHubLink": "https://github.com/izztnkr/Daily-Planner",
  "deployedLink": "https://izztnkr.github.io/Daily-Planner/",
  "techType": "MERN Stack",
  "tech1":"https://reactgifsportfolio.s3.us-east-2.amazonaws.com/javascriptlogo.png",
  "tech2":"https://reactgifsportfolio.s3.us-east-2.amazonaws.com/bootstraplogo.png",
  "tech3":"https://reactgifsportfolio.s3.us-east-2.amazonaws.com/vscodeLogo.png",
  "tech4":"https://reactgifsportfolio.s3.us-east-2.amazonaws.com/githubLogo.png", 
  "tech5":"",
  "tech6":"",
  "tech7":"",
  "tech8":"",
  "tech9":"",
  "tech10":"",
  "tech11":"",
  "tech12":""
}
]